### ISSUE TITLE
How to compress css ?

### ISSUE THREAD

**Issue by qingyun1029** [tkareine/jekyll-minibundle#10]
My configuration file is as follows :

minibundle:
  minifier_commands:
    css: _bin/remove_whitespace
    js: node_modules/.bin/uglifyjs -

The article mentioned : "And then specify the minifier command in _config.yml:"

````
minibundle:
  minifier_commands:
    css: _bin/remove_whitespace #this line !!!!!
    js: node_modules/.bin/uglifyjs -
````
However, I can not find the remove_whitespace in the path
https://github.com/tkareine/jekyll-minibundle/tree/master/test/fixture/site/_bin

Why not uglifycss, I accidentally found it ??

 It's me, again !

Thanks !!!
